package org.humint.field

import org.humint.field.data.Templates
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import java.io.File

/**
 * The one piece of logic that exists twice in two languages.
 *
 * A report's title is composed on the phone, from the pattern in the shared
 * registry, and the console composes the same title from the same pattern
 * when something posts without one. If the two implementations drift, the
 * failure is quiet and nasty: a vehicle sighting is filed under a title
 * nobody expects, and nobody notices until they go looking for it.
 *
 * So the expected answers are not written out here by hand. They are
 * generated by running the console's own compose_title over a list of cases
 * (see the header in title_cases.json) and committed as a fixture. This test
 * replays them through the Kotlin. A change to either side that is not
 * mirrored in the other fails here.
 *
 * Regenerate after changing either implementation:
 *
 *     python3 tools/gen_title_cases.py \
 *         android/app/src/test/resources/title_cases.json
 */
class TitleParityTest {

    companion object {
        @BeforeClass @JvmStatic
        fun loadRegistry() {
            // The console's own copy, not the one copied into assets — the
            // whole point is to catch the two drifting apart.
            //
            // Walked up to rather than reached for with a relative path:
            // Gradle runs unit tests with the working directory set to the
            // module (app/), Android Studio has been known to use the
            // project root, and a test that passes in one and fails in the
            // other teaches people to ignore it.
            val registry = findUpwards("api/field_templates.json")
            assertTrue(
                "api/field_templates.json not found above ${File("").absolutePath} — " +
                    "this test reads the console's own copy of the registry",
                registry != null
            )
            Templates.parse(registry!!.readText())
        }

        private fun findUpwards(relative: String): File? {
            var dir: File? = File("").absoluteFile
            repeat(6) {
                val candidate = File(dir, relative)
                if (candidate.isFile) return candidate
                dir = dir?.parentFile
            }
            return null
        }
    }

    @Test
    fun `titles match the console, case for case`() {
        // Off the test classpath rather than by path, for the same reason.
        val fixture = javaClass.getResource("/title_cases.json")
        assertTrue("title_cases.json is not on the test classpath; regenerate it",
                   fixture != null)
        val cases = JSONObject(fixture!!.readText()).getJSONArray("cases")
        assertTrue("the fixture is empty", cases.length() > 0)

        val mismatches = mutableListOf<String>()
        for (i in 0 until cases.length()) {
            val case = cases.getJSONObject(i)
            val template = Templates.byKey(case.getString("template"))
                ?: error("the fixture names a template the registry does not have")
            val fields = case.getJSONObject("fields").toMap()
            val actual = template.composeTitle(fields)
            val expected = case.getString("expected")
            if (actual != expected) {
                mismatches += "${case.getString("template")} ${case.getJSONObject("fields")}: " +
                    "console says \"$expected\", app says \"$actual\""
            }
        }
        assertEquals(
            "The app and the console no longer compose the same titles:\n" +
                mismatches.joinToString("\n"),
            emptyList<String>(), mismatches
        )
    }

    @Test
    fun `every template can produce a title from nothing`() {
        // A report has to be sendable even when the form was barely filled
        // in — a title is NOT NULL on the console, and refusing to send over
        // a missing one would lose the report.
        Templates.all.forEach { t ->
            assertTrue("${t.key} produced a blank title from an empty bag",
                       t.composeTitle(emptyMap()).isNotBlank())
        }
    }

    @Test
    fun `completeness matches what the registry asks for`() {
        val vehicle = Templates.byKey("vehicle")!!
        assertTrue("a plate alone should be enough for a vehicle",
                   vehicle.isComplete(mapOf("plate" to "ABC 1234")))
        assertTrue("a colour alone should be enough for a vehicle",
                   vehicle.isComplete(mapOf("color" to "white")))
        assertTrue("occupants alone identify nothing",
                   !vehicle.isComplete(mapOf("occupants" to "two")))
        assertEquals(
            "at least one of plate, make, model, colour",
            vehicle.whatIsMissing(mapOf("occupants" to "two"))
        )

        val sigint = Templates.byKey("sigint")!!
        assertTrue("a signal needs a frequency and a message",
                   !sigint.isComplete(mapOf("frequency" to "146.940")))
        assertTrue(sigint.isComplete(mapOf("frequency" to "146.940", "message" to "carrier")))
        assertEquals("what was said", sigint.whatIsMissing(mapOf("frequency" to "146.940")))
    }

    @Test
    fun `every template the console maps to a record can be filled in enough to make one`() {
        // Guards the interaction between require_any and the entity name
        // patterns: a template that can be marked complete but yields no
        // name would offer a record on the console and then make nothing.
        Templates.all.forEach { t ->
            val minimal = t.fields.filter { it.required }
                .associate { it.key to ("x" as Any?) }
                .toMutableMap()
            if (t.requireAny.isNotEmpty() && minimal.keys.none { it in t.requireAny }) {
                minimal[t.requireAny.first()] = "x"
            }
            assertTrue("${t.key}: a minimally-filled form is not complete",
                       t.isComplete(minimal))
            assertTrue("${t.key}: a minimally-filled form has no title",
                       t.composeTitle(minimal).isNotBlank())
        }
    }

    private fun JSONObject.toMap(): Map<String, Any?> =
        keys().asSequence().associateWith { key ->
            when (val v = get(key)) {
                is JSONArray -> (0 until v.length()).map { v.getString(it) }
                JSONObject.NULL -> null
                else -> v
            }
        }
}
